### ISSUE TITLE
Broken by upgrade to cloudfare tunnel addon 1.3

### ISSUE THREAD

**Issue by binzhou** [w35l3y/hassio-addons#12]
Just upgraded to 1.3  for cloudfare tunnel addon and the tunnel doesn't start. Errors with "Tunnel cedentials file '/data/tunnel.json' doesn't exist or is not a file.

Looking at the most recent commit, it looks like there's been a change in where the creds file is looked up. It use to be <tunnel-id>.json, but now we're explicitly expecting tunnel.json. But no upgrade path was defined so any existing users upgrading from pre-1.3 to 1.3 will be broken by this.

**Comment by binzhou** [comment]
Workaround was to uninstall then reinstall the addon to trigger cloudflared login again so the creds will be written to tunnel.json.

**Comment by w35l3y** [comment]
Exactly! I just fixed it, but you could reinstall the add-on just like you did.
