### ISSUE TITLE
Mensagem de repositório Invalido.

### ISSUE THREAD

**Issue by mdanilohome** [w35l3y/hassio-addons#13]
Amigo, estou entando instalar o ADD do Argo Tunel mas ao tentar adicionar o repositório está aparecendo uma mensagem de que o repositório está inválido.

**Comment by w35l3y** [comment]
Tutorial: https://github.com/w35l3y/hassio-addons/tree/main/cloudflare_tunnel#readme
Endereço do repositório a ser adicionado: https://github.com/w35l3y/hassio-addons

**Comment by mdanilohome** [comment]
É exatamente o endereço que estou utilizando!

**Comment by mdanilohome** [comment]
Veja na foto
![Repositório Argo Tunel](https://user-images.githubusercontent.com/86743538/166240588-18c7b42d-52a2-4d20-9eca-1d65f2900f37.jpg)

**Comment by w35l3y** [comment]
Parece ser um bug no Home Assistant.
Tentei **excluir** um repositório aleatório qualquer e apareceu este mesmo erro que o seu.

**Comment by w35l3y** [comment]
E agora acrescentei novamente e também deu esse erro que o seu, só que depois eu apertei **Ctrl+F5** e o repositório foi acrescentado.

**Comment by mdanilohome** [comment]
Fiz como você mencionou, pressionei F5 e a mensagem de erro desapareceu, mas o repositório apareceu com o nome " Unknown" . Seria iso mesmo? O problema agora é que na loja de ADD-On, pressiono o botão ADD On para inserir, coloco o nome Cloud na barra de pesquisa e não aparece o ADD para inserir.

**Comment by w35l3y** [comment]
Não... tem alguma coisa estranha aí.
Depois que apertei **Ctrl+F5**, os add-ons apareceram normal.

Aqui, a mensagem não sumiu, sempre que tento acrescentar ou remover repositório, a mensagem reaparece.
Mas ele está acrescentando normal.

Enfim, parece ser um bug no Home Assistant.
Se for abrir ticket lá, vai precisar dar mais detalhes.
Como por exemplo, versão do HA, registros de erro nos logs, ...

**Comment by w35l3y** [comment]
Toda vez que tento adicionar um repositório, aparece isso nos logs:
```
22-05-02 11:02:07 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
22-05-02 11:02:07 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
22-05-02 11:02:07 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.FREEZE
22-05-02 11:02:07 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-05-02 11:02:07 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.FREEZE
22-05-02 11:02:07 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-05-02 11:02:07 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - CoreState.FREEZE
```

**Comment by w35l3y** [comment]
Ó, aqui tudo voltou ao normal agora.

![image](https://user-images.githubusercontent.com/963510/166252353-82eeea3c-9035-4c33-b65d-d836bf60eaad.png)

O passo-a-passo que eu fiz foi o seguinte:
* Cliquei no botão "REBOOT HOST"
  * Quando fiz isso, voltei na "Add-on Store" e tentei remover um repositório e não aconteceu nada aparentemente.
  * Nem removeu, nem apareceu mensagem de erro... nada.
* Depois eu voltei no "System", cliquei em "RESTART SUPERVISOR"
  * Voltei na "Add-on Store" e apertei **Ctrl+F5** e isso fez com que a página ficasse um um "loading" interminável.
  * Daí eu cliquei no "..." do canto superior da tela e em "Repositories".
  * A lista de repositórios simplesmente estava completamente vazia.
  * Então eu acrescentei 1 repositório qualquer e ele foi acrescentado imediatamente e o "loading" parou.
  * Só que a lista continuava só com o único repositório que acrescentei.
* Voltei no "System", olhei os logs, não encontrei nada demais, cliquei "RELOAD SUPERVISOR" e voltei no "Add-on Store"
  * Dessa vez todos os repositórios que tinham antes reapareceram, porém, a lista de respositórios continuava apenas com os que eu havia acrescentado
  * Então eu inclui manualmente todos os repositórios que eu já tinha.
