### ISSUE TITLE
ERRO 400 ao ao executar o endereço https  com o subdomínio criado.

### ISSUE THREAD

**Issue by mdanilohome** [w35l3y/hassio-addons#14]
Consegui instalar o repositório, fiz e conferi todos os passos de configuração para utilização do acesso remoto através do Coldflare mas está apresentando erro 400.

Configuração do Coldflare:

no-autoupdate: true
originRequest: {}
metrics: localhost:41705
tunnel: homeassistant
ingress:
  - hostname: tun.mdaniloha.tk
    service: http://192.168.XX.XX:8123
  - service: http_status:404

Segue o LOG:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] cloudflare.sh: executing... 
Validating rules from /data/options.json
OK
/root/.cloudflared:
cert.pem
options.json
tunnel.json
You have an existing certificate at /root/.cloudflared/cert.pem which login would overwrite.
If this is intentional, please move or delete that file then run this command again.
You can obtain more detailed information for each tunnel with `cloudflared tunnel info <name/uuid>`
ID                                   NAME          CREATED              CONNECTIONS 
c49280da-9d3a-4828-af4c-04820698eb15 homeassistant 2022-05-02T22:09:06Z             
there should only be 1 non-deleted Tunnel named null
Tunnel credentials written to /root/.cloudflared/tunnel.json. Keep this file secret. To revoke these credentials, delete the tunnel.

Created tunnel homeassistant with id 00b948a5-6830-4bf0-8e28-146f8f9d10e0
2022-05-02T23:29:05Z INF Added CNAME tun.mdaniloha.tk which will route to this tunnel tunnelID=00b948a5-6830-4bf0-8e28-146f8f9d10e0
[cont-init.d] cloudflare.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-05-02T23:29:05Z INF Starting tunnel tunnelID=00b948a5-6830-4bf0-8e28-146f8f9d10e0
2022-05-02T23:29:05Z INF Version 2022.4.1
2022-05-02T23:29:05Z INF GOOS: linux, GOVersion: go1.17.5, GoArch: amd64
2022-05-02T23:29:05Z INF Settings: map[config:/data/options.json cred-file:/data/tunnel.json credentials-file:/data/tunnel.json metrics:localhost:41705 no-autoupdate:true]
2022-05-02T23:29:05Z INF Generated Connector ID: 1097929e-10df-4e14-abc4-429b8c7d93fb
2022-05-02T23:29:05Z INF Initial protocol quic
2022-05-02T23:29:05Z INF Starting metrics server on 127.0.0.1:41705/metrics
2022/05/02 20:29:06 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2022-05-02T23:29:06Z INF Connection ef9309e5-854b-42b9-9359-756ed9a0908b registered connIndex=0 location=GIG
2022-05-02T23:29:07Z INF Connection ae20dd92-7cc3-411f-b0a7-dfd6fc1cb3ce registered connIndex=1 location=GRU
2022-05-02T23:29:08Z INF Connection 048d21bf-84a0-4d3c-8331-fb737c54d3ad registered connIndex=2 location=GIG
2022-05-02T23:29:09Z INF Connection a82faf94-66e6-4c3e-b77d-57643f00ffc3 registered connIndex=3 location=GRU

**Comment by w35l3y** [comment]
Tentou o que está escrito no final do tutorial na parte que fala de erros comuns ?

https://github.com/w35l3y/hassio-addons/tree/main/cloudflare_tunnel#common-errors

```
400: Bad Request
Update trusted_proxies with the IP or range that is shown in the HA Logs (Sidebar Configurations > Logs).
```

**Comment by mdanilohome** [comment]
Com relação as linhas de http trusted proxies, inseri no configuration.yaml exatamente como estava no tutorial, conforme você descreveu acima.

Quanto a atualização do IP no trusted proxies, não consegui entender. Poderia me explicar melhor? Fala de uma barra lateral de configuração. Não consegui entender onde fica esta barra.

**Comment by w35l3y** [comment]
`Configuration > Settings > Logs` e/ou `Configuration > Add-ons, Backups & Supervisor > System > Log provider`

Barra lateral
![image](https://user-images.githubusercontent.com/963510/166390311-13af2053-222c-4943-9dfa-52ffe16f370c.png)

Configuration
![image](https://user-images.githubusercontent.com/963510/166390335-4bb4ed5e-d1a7-4b9c-8ead-ebd18132c514.png)
e/ou
![image](https://user-images.githubusercontent.com/963510/166390353-fd451deb-b965-4dff-8a52-e8b051caf072.png)

Cabeçalho do Settings
![image](https://user-images.githubusercontent.com/963510/166390380-4dba1408-9733-4090-b189-95171254f1a2.png)

Cabeçalho do Add-ons, Backups & Supervisor
![image](https://user-images.githubusercontent.com/963510/166390409-4d0d206b-eb88-4b34-98cb-f2c8a36b95d8.png)

System
![image](https://user-images.githubusercontent.com/963510/166390434-6f9e11ce-f8b4-4d86-b668-b06b1ca267f5.png)

**Comment by mdanilohome** [comment]
Seguem anexas as duas linhas que identifiquei no LOG.
Com essas informações qual o valor de IP ou  Range que devo mudar? Onde faço a alteração? Desculpe as perguntas elementares mas sou iniciante.
![Linha de LOG 2](https://user-images.githubusercontent.com/86743538/166391132-5e6f5b37-7909-4f40-b5ce-3c8a8e700b37.jpg)
![Linha de LOG 1](https://user-images.githubusercontent.com/86743538/166391133-0b066568-4032-42ca-91fd-497d02b9edbb.jpg)

**Comment by w35l3y** [comment]
Nenhuma dessas linhas diz respeito a bloqueios de acesso.
Precisa procurar em todos os logs alguma mensagem que fale de que um determinado IP ou intervalo foi bloqueado.

**Comment by mdanilohome** [comment]
Estou te enviando o LOG completo e não aparece pelo menos a meu ver nenhuma linha citando bloqueio de IP.
![LOG Completo](https://user-images.githubusercontent.com/86743538/166391681-fdf06d4c-01a3-40e7-8d17-b9d6bff94003.jpg)

**Comment by mdanilohome** [comment]
Tentei acessar novamente e surgiram as linhas em verde do arquivo anexo.
![LOG atualizado](https://user-images.githubusercontent.com/86743538/166391770-b54e4687-e8c6-42d8-86af-6b0dc3b367c1.jpg)

**Comment by w35l3y** [comment]
> ![LOG Completo](https://user-images.githubusercontent.com/86743538/166391681-fdf06d4c-01a3-40e7-8d17-b9d6bff94003.jpg)
Tu conseguiu ler ?

Nesse caso, fica MUITO mais fácil se copiar e colar o texto em si, sem ser por meio de print.
Verificou também os logs do próprio add-on ?

Bom, minha sugestão é você limpar os logs e em seguida fazer uma requisição.
Assim, os logs só terão os erros mais recentes.
Não sei se você tem uma configuração normal de 1 modem/roteador ou 1 modem + 1 roteador sendo access point ou bridge.
Em resumo, esse erro é porque tem alguma coisa no meio do caminho bloqueando o acesso.
Não é defeito no add-on.

**Comment by w35l3y** [comment]
Na parte de "System", existe outros "Log providers"
Pode ser que a mensagem de erro esteja em algum dos outros, por exemplo, "Supervisor", "Core" ou "Host".

Você também pode optar por aumentar o nível de log de tudo ou restringir pros pacotes relacionados...
```
logger:
  default: debug
```

Essa parte eu realmente não vou conseguir te ajudar.

**Comment by mdanilohome** [comment]
Você fez uma observação importante! Eu uso um modem da operadora Claro para receber a internet e a este modem tenho 3 roteadores TP-Link AX 3000 em rede mesh. O Roteador principal está conectado por cabo no modem e sai um cabo do modem e entra num switch, onde na numa das portas do switch está conectado o servidor do meu HA. O meu computador gamer que estou utilizando para tentar conectar ao HA está conectado na porta Gigabit deste switch.

**Comment by w35l3y** [comment]
Pois bem, se o erro não aparece entre os logs no HA, ele pode mesmo estar sendo barrado em algum caminho aí nessa sua configuração de rede.
Isso está completamente fora do escopo do funcionamento do add-on.
Por ora, vou fechar o ticket, mas se encontrar algo que eu possa evoluir no tutorial, só comentar.

Boa caçada.

**Comment by mdanilohome** [comment]
OK. Obrigado pela ajuda. Amanhã vou ter o apoio de um amigo que conhece em profundidade  redes e vamos tentar ver se conseguimos identificar algo.
