### ISSUE TITLE
empty page 

### ISSUE THREAD

**Issue by lowrisk75** [w35l3y/hassio-addons#2]
not sure what do I do wrong, but at first I have a firewall issue which I resolved. but after than, it would only load an empty page, just white background nothing at all, whatever the client I'm using....
I don't see any issue with my config.
> when I copy the IP from the configuration (local IP+ port) it's redirecting just fine, its just the Argo link/or CNAM redirection that doesn't work.

**Comment by lowrisk75** [comment]
-- it's seems that I'm automatically redirected to https (which might be a settings in my cloudflare account)

**Comment by w35l3y** [comment]
did it solve the problem ?
are you following the steps of domain owner ?

**Comment by lowrisk75** [comment]
> did it solve the problem ?
> are you following the steps of domain owner ?

Not yet, yes I did follow these steps. Might be something with the https redirection while the docker is configured for http. I’ll look more into this tomorrow.

**Comment by w35l3y** [comment]
I only tested it on HassOS

**Comment by michaelcarvalho86** [comment]
> not sure what do I do wrong, but at first I have a firewall issue which I resolved. but after than, it would only load an empty page, just white background nothing at all, whatever the client I'm using.... I don't see any issue with my config.
> 
> > when I copy the IP from the configuration (local IP+ port) it's redirecting just fine, its just the Argo link/or CNAM redirection that doesn't work.

Which rules do you use on your firewall?

Or what have you done to solve the firewall issue?

**Comment by w35l3y** [comment]
Closed due to inactivity
