### ISSUE TITLE
s6-overlay-suexec

### ISSUE THREAD

**Issue by nemiro-TECH** [w35l3y/hassio-addons#20]
On add-on start, nothing happens, this shows on log:

**s6-overlay-suexec: fatal: can only run as pid 1**

RBPi4
Home Assistant 2022.10.2
Supervisor 2022.10.0
Operating System 9.0
Frontend: 20221006.0 - latest

**Comment by w35l3y** [comment]
What add-on are you talking about?

**Comment by nemiro-TECH** [comment]
Whatsapp add-on

Em seg., 10 de out. de 2022 às 13:39, w35l3y ***@***.***>
escreveu:

**Comment by w35l3y** [comment]
Duplicate of #19

**Comment by nemiro-TECH** [comment]
I suggest you mark this add-on as not maintained any more, so no one
opens issues for it.

Em seg., 10 de out. de 2022 às 14:42, w35l3y ***@***.***>
escreveu:
