### ISSUE TITLE
Not able to install whatsapp

### ISSUE THREAD

**Issue by sheminasalam** [w35l3y/hassio-addons#21]
Getting the following error popup.

The command '/bin/ash -o pipefail -c ARCH="${BUILD_ARCH}" && if [[ "${BUILD_ARCH}" = "amd64" ]]; then ARCH="x86_64"; fi && echo $ARCH > /etc/apk/arch && apk add --no-cache --update mesa-egl mesa-gles nodejs npm chromium && npm install && chmod +x run.sh' returned a non-zero code: 1

I had the same error with cloudflare but it somehow rectified itself but this is not.

**Comment by w35l3y** [comment]
This add-on is not being maintaned.

At that moment, the add-on was suffering of memory leak that I was not able to detect the fix. It was freezing HA recurrently (every 2 days or so).
In the middle time, HA changed the way add-ons were started.
Then, the [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js/)  changed completely its API to work with multiple sessions and stopped the add-on.

So, there are too many things to fix and I am not interested anymore.
