### ISSUE TITLE
Default hostname

### ISSUE THREAD

**Issue by j2ghz** [w35l3y/hassio-addons#8]
https://github.com/w35l3y/hassio-addons/blob/edf09609f7b8d64f8b51dd5d21f041633e0ef24a/cloudflare_tunnel/config.json#L18
In my experience, `homeassistant` works (without local), because that's the internal name of the docker container in HAOS.
Tested on the official RPi 3 and virtual machine installation methods.

**Comment by w35l3y** [comment]
I can confirm it also worked to me without ".local"
Thanks!

I will update the code.
